export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const GET_ALL_ACTOR = 'GET_ALL_ACTOR'
export const GET_ALL_DIRECTOR = 'GET_ALL_DIRECTOR'
export const GET_ALL_NEW = 'GET_ALL_NEW'
export const SEARCH_RESULT = 'SEARCH_RESULT'